#!/bin/bash
set -e

echo "Initializing PostgreSQL database user..."

# Create user only if it doesn't exist
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="$POSTGRES_DB" <<-EOSQL
	    DO \$\$
	    BEGIN
	        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$PGUSER') THEN
	            CREATE USER $PGUSER WITH PASSWORD '$PGPASSWORD';
				GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $PGUSER;
	        END IF;
	    END \$\$;
EOSQL

# Grant CREATE privileges to docker user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="$POSTGRES_DB" <<-EOSQL
	    GRANT USAGE, CREATE ON SCHEMA public TO $PGUSER;
		GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $PGUSER;
		GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $PGUSER;
		GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $PGUSER;
		ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO $PGUSER;
		ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO $PGUSER;
		ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO $PGUSER;
EOSQL

echo "PostgreSQL initialization complete."
